services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sag_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://sag_user:sag_password@db:5432/sag_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: sag_db
    environment:
      - POSTGRES_USER=sag_user
      - POSTGRES_PASSWORD=sag_password
      - POSTGRES_DB=sag_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sag_user -d sag_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: